version: '3.7'
services:
  db:
    image: 'postgres:12'
    ports:
      - '5433:5432'
    expose:
      - 5433
    environment:
      {
        POSTGRES_USER: 'blog-user',
        POSTGRES_PASSWORD: 'password',
        POSTGRES_DB: 'blog-prod',
      }
